# 🚗 Automobile Dataset Cleaning and Preprocessing Project

## Introduction

Data quality is one of the most important factors in any data analytics or machine learning project. Raw datasets often contain missing values, inconsistent formats, duplicate information, and categorical variables that need to be transformed before analysis can begin.

In this project, the Automobile dataset from the UCI Machine Learning Repository was imported, explored, cleaned, and transformed into a machine-learning-ready dataset. The project focuses on handling missing values, data standardization, feature engineering, and converting categorical variables into numerical indicators.

## 🎯 Project Objectives

The main objectives of this project are:

- Import and explore the Automobile dataset.
- Understand the dataset structure and dimensions.
- Identify missing values and data quality issues.
- Replace invalid values with proper null values.
- Handle missing numerical and categorical data.
- Create new features through data transformation.
- Convert categorical variables into dummy variables.
- Prepare the dataset for future analysis and machine learning tasks.
- Export the cleaned dataset for further use.

## Importing and Loading the Dataset

The first step in any data analysis project is importing the required libraries and loading the dataset into a DataFrame. This allows us to explore, clean, and manipulate the data using Pandas and NumPy.

In [1]:
import pandas as pd
import numpy as np

In [2]:
url="https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data"
allo =pd.read_csv(url, header=None)
allo

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

# Understanding the Dataset Structure

Before cleaning the data, it is important to understand its structure. We examine the number of rows and columns and preview the first few records to gain an initial understanding of the dataset.

In [3]:
allo.shape

(205, 26)

In [4]:
allo.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

# Assigning Meaningful Column Names

The dataset was imported without descriptive column names. Assigning meaningful column names improves readability and makes subsequent analysis easier to understand and maintain.

In [5]:
import pandas as pd

# Define column names from UCI dataset description
columns = [
    "symboling", "normalized_losses", "make", "fuel_type", "aspiration",
    "num_doors", "body_style", "drive_wheels", "engine_location",
    "wheel_base", "length", "width", "height", "curb_weight",
    "engine_type", "num_cylinders", "engine_size", "fuel_system",
    "bore", "stroke", "compression_ratio", "horsepower",
    "peak_rpm", "city_mpg", "highway_mpg", "price"
]

# Read the data
allo = pd.read_csv(url, names=columns)

# Check first rows
allo

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

# Handling Missing Values

In this dataset, missing values are represented by question marks (?). Since Pandas does not automatically recognize these as missing values, they must be converted to NaN (Not a Number) so they can be properly identified and treated during the cleaning process.

In [6]:
import numpy as np

# replace "?" to NaN
allo.replace("?",np.nan,inplace=True)
allo

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

# Identifying Missing Data

After converting invalid entries to NaN values, we assess the dataset to determine which columns contain missing values and the extent of missingness in each feature.

In [7]:
allo.isnull().sum()

symboling             0
normalized_losses    41
make                  0
fuel_type             0
aspiration            0
num_doors             2
body_style            0
drive_wheels          0
engine_location       0
wheel_base            0
length                0
width                 0
height                0
curb_weight           0
engine_type           0
num_cylinders         0
engine_size           0
fuel_system           0
bore                  4
stroke                4
compression_ratio     0
horsepower            2
peak_rpm              2
city_mpg              0
highway_mpg           0
price                 4
dtype: int64

In [8]:
allo['normalized_losses']

0      NaN
1      NaN
2      NaN
3      164
4      164
      ...
200     95
201     95
202     95
203     95
204     95
Name: normalized_losses, Length: 205, dtype: object

# Imputing Missing Values in Normalized Losses

The normalized_losses column contains missing numerical values. To preserve the dataset and avoid losing observations, missing entries are replaced using the mean value of the column. Mean imputation is commonly used when dealing with continuous numerical variables.

In [9]:
avg_normal_loss=allo['normalized_losses'].astype('float').mean(axis=0)
avg_normal_loss

np.float64(122.0)

In [10]:
allo['normalized_losses'].replace(np.nan,avg_normal_loss, inplace=True)
allo.head()

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [11]:
allo.isnull().sum()

symboling            0
normalized_losses    0
make                 0
fuel_type            0
aspiration           0
num_doors            2
body_style           0
drive_wheels         0
engine_location      0
wheel_base           0
length               0
width                0
height               0
curb_weight          0
engine_type          0
num_cylinders        0
engine_size          0
fuel_system          0
bore                 4
stroke               4
compression_ratio    0
horsepower           2
peak_rpm             2
city_mpg             0
highway_mpg          0
price                4
dtype: int64

# Handling Missing Values in Categorical Data

The num_doors column is a categorical feature. Since calculating an average is not meaningful for categorical variables, missing values are replaced using the mode, which represents the most frequently occurring category in the dataset.

In [12]:
allo['num_doors']

0       two
1       two
2       two
3      four
4      four
       ...
200    four
201    four
202    four
203    four
204    four
Name: num_doors, Length: 205, dtype: object

In [13]:
allo['num_doors'].value_counts()

num_doors
four    114
two      89
Name: count, dtype: int64

In [14]:
allo['num_doors'] = allo['num_doors'].fillna('four')

In [15]:
allo.isnull().sum()

symboling            0
normalized_losses    0
make                 0
fuel_type            0
aspiration           0
num_doors            0
body_style           0
drive_wheels         0
engine_location      0
wheel_base           0
length               0
width                0
height               0
curb_weight          0
engine_type          0
num_cylinders        0
engine_size          0
fuel_system          0
bore                 4
stroke               4
compression_ratio    0
horsepower           2
peak_rpm             2
city_mpg             0
highway_mpg          0
price                4
dtype: int64

# Imputing Missing Values in Bore

The bore feature contains a small number of missing numerical values. These values are replaced using the column mean to maintain consistency while minimizing the impact on the overall distribution of the data.

In [16]:
allo['bore']

0      3.47
1      3.47
2      2.68
3      3.19
4      3.19
       ...
200    3.78
201    3.78
202    3.58
203    3.01
204    3.78
Name: bore, Length: 205, dtype: object

In [17]:
avg_bore =allo['bore'].astype('float').mean(axis=0).round(2)
avg_bore

np.float64(3.33)

In [18]:
allo['bore'].replace(np.nan,avg_bore,inplace=True)

In [19]:
allo.isnull().sum()

symboling            0
normalized_losses    0
make                 0
fuel_type            0
aspiration           0
num_doors            0
body_style           0
drive_wheels         0
engine_location      0
wheel_base           0
length               0
width                0
height               0
curb_weight          0
engine_type          0
num_cylinders        0
engine_size          0
fuel_system          0
bore                 0
stroke               4
compression_ratio    0
horsepower           2
peak_rpm             2
city_mpg             0
highway_mpg          0
price                4
dtype: int64

## Imputing Missing Values in Stroke

To ensure data completeness, missing values in the stroke column are replaced with the average stroke value calculated from the available observations.

In [20]:
allo['stroke']

0      2.68
1      2.68
2      3.47
3      3.40
4      3.40
       ...
200    3.15
201    3.15
202    2.87
203    3.40
204    3.15
Name: stroke, Length: 205, dtype: object

In [21]:
avg_stroke =allo['stroke'].astype("float").mean(axis=0).round(2)
avg_stroke

np.float64(3.26)

In [22]:
allo['stroke'].replace(np.nan, avg_stroke, inplace=True)

In [23]:
allo.isnull().sum()

symboling            0
normalized_losses    0
make                 0
fuel_type            0
aspiration           0
num_doors            0
body_style           0
drive_wheels         0
engine_location      0
wheel_base           0
length               0
width                0
height               0
curb_weight          0
engine_type          0
num_cylinders        0
engine_size          0
fuel_system          0
bore                 0
stroke               0
compression_ratio    0
horsepower           2
peak_rpm             2
city_mpg             0
highway_mpg          0
price                4
dtype: int64

# Imputing Missing Values in Horsepower

Horsepower is an important numerical feature that influences vehicle performance. Missing values are replaced with the mean horsepower value to maintain the integrity of the dataset.

In [24]:
allo["horsepower"]

0      111
1      111
2      154
3      102
4      115
      ...
200    114
201    160
202    134
203    106
204    114
Name: horsepower, Length: 205, dtype: object

In [25]:
avg_horse =allo["horsepower"].astype("float").mean(axis=0).round(2)
avg_horse

np.float64(104.26)

In [26]:
allo["horsepower"].replace(np.nan,avg_horse,inplace=True)

In [27]:
allo.isnull().sum()

symboling            0
normalized_losses    0
make                 0
fuel_type            0
aspiration           0
num_doors            0
body_style           0
drive_wheels         0
engine_location      0
wheel_base           0
length               0
width                0
height               0
curb_weight          0
engine_type          0
num_cylinders        0
engine_size          0
fuel_system          0
bore                 0
stroke               0
compression_ratio    0
horsepower           0
peak_rpm             2
city_mpg             0
highway_mpg          0
price                4
dtype: int64

# Imputing Missing Values in Peak RPM

Missing values in the peak_rpm column are replaced using the column average. This approach preserves all observations while maintaining a reasonable representation of the feature.

In [28]:
allo["peak_rpm"]

0      5000
1      5000
2      5000
3      5500
4      5500
       ...
200    5400
201    5300
202    5500
203    4800
204    5400
Name: peak_rpm, Length: 205, dtype: object

In [29]:
avg_peak =allo["peak_rpm"].astype("float").mean(axis=0).round(2)
avg_peak

np.float64(5125.37)

In [30]:
allo["peak_rpm"].replace(np.nan,avg_peak,inplace=True)

In [31]:
allo.isnull().sum()

symboling            0
normalized_losses    0
make                 0
fuel_type            0
aspiration           0
num_doors            0
body_style           0
drive_wheels         0
engine_location      0
wheel_base           0
length               0
width                0
height               0
curb_weight          0
engine_type          0
num_cylinders        0
engine_size          0
fuel_system          0
bore                 0
stroke               0
compression_ratio    0
horsepower           0
peak_rpm             0
city_mpg             0
highway_mpg          0
price                4
dtype: int64

# Removing Records with Missing Prices

Price is the target variable and one of the most important features in the dataset. Records with missing prices are removed because imputing the target variable could introduce bias and reduce the reliability of future analyses.

In [32]:
allo.dropna(subset=["price"],inplace=True)

In [33]:
allo.head()

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

# Feature Engineering: Fuel Consumption Conversion

Fuel efficiency is commonly expressed using different measurement systems. To improve interpretability and standardization, city fuel consumption is converted from miles per gallon (MPG) to liters per 100 kilometers (L/100km) by creating a new feature.

In [34]:

#Question #1:
#According to the example above, transform mpg to L/100km in the column of "city-mpg" and change the name of column to "city-L/100km".~
allo['city-L/km']=235/allo['city_mpg']
allo.head()

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price,city-L/km
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,13495,11.190476
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,16500,11.190476
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,mpfi,2.68,3.47,9.0,154,5000,19,26,16500,12.368421
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,mpfi,3.19,3.40,10.0,102,5500,24,30,13950,9.791667
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,mpfi,3.19,3.40,8.0,115,5500,18,22,17450,13.055556

In [35]:
allo["fuel_type"]

0         gas
1         gas
2         gas
3         gas
4         gas
        ...
200       gas
201       gas
202       gas
203    diesel
204       gas
Name: fuel_type, Length: 201, dtype: object

# Encoding Categorical Variables: Fuel Type

Machine learning algorithms generally require numerical inputs. The fuel_type feature is transformed into dummy variables, allowing categorical information to be represented in a numerical format while preserving its meaning.

pd.get_dummies(allo[" "]) to get a dummie variable

# Question #4:
Similar to before, create an indicator variable for the column "aspiration"

In [36]:
dummy_variable_1 = pd.get_dummies(allo["fuel_type"])
dummy_variable_1.head()

   diesel   gas
0   False  True
1   False  True
2   False  True
3   False  True
4   False  True

In [37]:
#Change the column names for clarity:
dummy_variable_1.rename(columns={'gas':'fuel-type-gas', 'diesel':'fuel-type-diesel'}, inplace=True)
dummy_variable_1.head()

   fuel-type-diesel  fuel-type-gas
0             False           True
1             False           True
2             False           True
3             False           True
4             False           True

In [38]:
# merge data frame "allo" and "dummy_variable_1" 
allo= pd.concat([allo, dummy_variable_1], axis=1)

# drop original column "fuel-type" from "df"
allo.drop("fuel_type", axis = 1, inplace=True)

In [39]:
allo.head()

,symboling,normalized_losses,make,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,length,...,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price,city-L/km,fuel-type-diesel,fuel-type-gas
0,3,122.0,alfa-romero,std,two,convertible,rwd,front,88.6,168.8,...,2.68,9.0,111,5000,21,27,13495,11.190476,False,True
1,3,122.0,alfa-romero,std,two,convertible,rwd,front,88.6,168.8,...,2.68,9.0,111,5000,21,27,16500,11.190476,False,True
2,1,122.0,alfa-romero,std,two,hatchback,rwd,front,94.5,171.2,...,3.47,9.0,154,5000,19,26,16500,12.368421,False,True
3,2,164,audi,std,four,sedan,fwd,front,99.8,176.6,...,3.40,10.0,102,5500,24,30,13950,9.791667,False,True
4,2,164,audi,std,four,sedan,4wd,front,99.4,176.6,...,3.40,8.0,115,5500,18,22,17450,13.055556,False,True

# Encoding Categorical Variables: Aspiration

The aspiration feature contains categorical values that must be converted into numerical representations. Dummy variables are created to enable future statistical analysis and machine learning applications.

In [40]:
allo['aspiration']

0        std
1        std
2        std
3        std
4        std
       ...
200      std
201    turbo
202      std
203    turbo
204    turbo
Name: aspiration, Length: 201, dtype: object

In [41]:
dummy_v = pd.get_dummies(allo['aspiration'])
dummy_v

       std  turbo
0     True  False
1     True  False
2     True  False
3     True  False
4     True  False
..     ...    ...
200   True  False
201  False   True
202   True  False
203  False   True
204  False   True

[201 rows x 2 columns]

In [42]:
dummy_v.rename(columns={'std':'aspiration-std', 'turbo':'aspiration-turbo'}, inplace=True)
dummy_v.head()

   aspiration-std  aspiration-turbo
0            True             False
1            True             False
2            True             False
3            True             False
4            True             False

In [43]:
# merge data frame "cars" and "dummy_variable_1" 
allo = pd.concat([allo, dummy_v], axis=1)

# drop original column "fuel-type" from "df"
allo.drop("aspiration", axis = 1, inplace=True)

In [44]:
allo.head()

,symboling,normalized_losses,make,num_doors,body_style,drive_wheels,engine_location,wheel_base,length,width,...,horsepower,peak_rpm,city_mpg,highway_mpg,price,city-L/km,fuel-type-diesel,fuel-type-gas,aspiration-std,aspiration-turbo
0,3,122.0,alfa-romero,two,convertible,rwd,front,88.6,168.8,64.1,...,111,5000,21,27,13495,11.190476,False,True,True,False
1,3,122.0,alfa-romero,two,convertible,rwd,front,88.6,168.8,64.1,...,111,5000,21,27,16500,11.190476,False,True,True,False
2,1,122.0,alfa-romero,two,hatchback,rwd,front,94.5,171.2,65.5,...,154,5000,19,26,16500,12.368421,False,True,True,False
3,2,164,audi,four,sedan,fwd,front,99.8,176.6,66.2,...,102,5500,24,30,13950,9.791667,False,True,True,False
4,2,164,audi,four,sedan,4wd,front,99.4,176.6,66.4,...,115,5500,18,22,17450,13.055556,False,True,True,False

## Question #5:
Merge the new dataframe to the original dataframe, then drop the column 'aspiration'.

In [45]:
# Write your code below and press Shift+Enter to execute 

# merge the new dataframe to the original datafram
allo = pd.concat([allo, dummy_variable_1], axis=1)

# drop original column "aspiration" from "df"
#allo.drop('aspiration', axis = 1, inplace=True)

In [46]:
allo.head()

,symboling,normalized_losses,make,num_doors,body_style,drive_wheels,engine_location,wheel_base,length,width,...,city_mpg,highway_mpg,price,city-L/km,fuel-type-diesel,fuel-type-gas,aspiration-std,aspiration-turbo,fuel-type-diesel,fuel-type-gas
0,3,122.0,alfa-romero,two,convertible,rwd,front,88.6,168.8,64.1,...,21,27,13495,11.190476,False,True,True,False,False,True
1,3,122.0,alfa-romero,two,convertible,rwd,front,88.6,168.8,64.1,...,21,27,16500,11.190476,False,True,True,False,False,True
2,1,122.0,alfa-romero,two,hatchback,rwd,front,94.5,171.2,65.5,...,19,26,16500,12.368421,False,True,True,False,False,True
3,2,164,audi,four,sedan,fwd,front,99.8,176.6,66.2,...,24,30,13950,9.791667,False,True,True,False,False,True
4,2,164,audi,four,sedan,4wd,front,99.4,176.6,66.4,...,18,22,17450,13.055556,False,True,True,False,False,True

# Conclusion

This project focused on cleaning and preparing the Automobile dataset for analysis. Missing values were identified and handled appropriately using statistical imputation techniques and data filtering methods. Feature engineering was performed to improve data usability, and categorical variables were transformed into machine-readable formats through one-hot encoding.

The resulting dataset is cleaner, more consistent, and ready for advanced analytical tasks such as exploratory data analysis, data visualization, and predictive modeling. Proper data preprocessing is a critical step in the data analytics workflow, as the quality of insights generated depends heavily on the quality of the underlying data.

# Exporting the Clean Dataset

After completing all preprocessing steps, the cleaned dataset is exported to a CSV file. This ensures that the prepared data can be reused for exploratory data analysis, visualization, and machine learning without repeating the cleaning process.

In [50]:
allo.to_csv('clean_df.csv')